name: sonoff
description: A simple command-line application.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: ^2.17.0


dependencies:
 http: ^0.13.4
 crypto: ^3.0.2

 network_tools:
   git:
     ref: dev
     url: https://github.com/guyluz11/network_tools.git
     path: network_tools

dev_dependencies:
  lints: ^2.0.0
